### ISSUE TITLE
Implement "edit and resend"

### ISSUE THREAD

**Issue by fflorent** [firebug/rdp-inspector#45]
I would really love to have a way to edit and resend an RDP packet (like the DevTools do in the Network panel).

Here is a test case:
1. Something weird happens on the DevTools or on my extension, I open the RDP Inspector to inspect the packets
2. I identify the packet and identify a potential malformation of it (bad or missing property)
3. I right-click on the packet and select "edit and resend the packet" => I am in the "Send packet" side-panel, with the properties of the packet pre-filled
4. I edit the properties
5. I send the packet and observe the behavior.

version: 1.0.4.1-signed

Florent

**Comment by rpl** [comment]
This is definitely a feature that we want to implement.

We've previously reverted a simple implementation because it didn't always behave as a user will expect it to, so it is useful to add some reference here as context about it:

- reverted commit: https://github.com/firebug/rdp-inspector/commit/55aa0752d9c5e32468038253bce2eaa9f4df2509
- related pull request: https://github.com/firebug/rdp-inspector/pull/24
